sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t etrapets/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true etrapets/docker-react npm run test